
messageName = { 

	"'A journey of one thousand miles starts with the first step' - Laozi",
	"''No act of kindness, no matter how small, is ever wasted' - Aepos",
	"'The only way to do great work is to love what you do' – Steve Jobs",
	"'Success is not final, failure is not fatal: It is the courage to continue that counts' – Winston Churchill",
	"'It does not matter how slowly you go, as long as you do not stop' – Confucius",
	"'The harder you work for something, the greater you’ll feel when you achieve it' – Anonymous",
	"'Believe you can and you’re halfway there' – Theodore Roosevelt",
	"'Your time is limited, don’t waste it living someone else’s life' – Steve Jobs",
	"'Act as if what you do makes a difference. It does' – William James",
	"'Success is not how high you have climbed, but how you make a positive difference to the world' – Roy T. Bennett",
	"'You are never too old to set another goal or to dream a new dream' – C.S. Lewis",
	"'Everything you can imagine is real' – Pablo Picasso",
	"'It always seems impossible until it’s done' – Nelson Mandela",
	"'The future belongs to those who believe in the beauty of their dreams' – Eleanor Roosevelt",
	"'In the middle of every difficulty lies opportunity' – Albert Einstein",
	"'The only limit to our realization of tomorrow is our doubts of today' – Franklin D. Roosevelt",
	"'Do what you can with all you have, wherever you are' – Theodore Roosevelt",
	"'Don’t wait. The time will never be just right' – Napoleon Hill",
	"'Success is not the key to happiness. Happiness is the key to success' – Albert Schweitzer",
	"'Hardships often prepare ordinary people for an extraordinary destiny' – C.S. Lewis",
	"'Keep your face always toward the sunshine—and shadows will fall behind you' – Walt Whitman",
	"'The best way to predict your future is to create it' – Abraham Lincoln",
	"'It’s not whether you get knocked down, it’s whether you get back up' – Vince Lombardi",
	"'Don’t watch the clock; do what it does. Keep going' – Sam Levenson",
	"'You are braver than you believe, stronger than you seem, and smarter than you think' – A.A. Milne",
	"'You miss 100% of the shots you don’t take' – Wayne Gretzky",
	"'The way to get started is to quit talking and begin doing' – Walt Disney",
	"'Success doesn’t just find you. You have to go out and get it' – Anonymous",
	"'Work hard in silence, let your success be your noise' – Frank Ocean",
	"'The only place where success comes before work is in the dictionary' – Vidal Sassoon",
	"'Don’t limit your challenges. Challenge your limits' – Anonymous",
	"'Do something today that your future self will thank you for' – Anonymous",
	"'Dream it. Wish it. Do it' – Anonymous",
	"'The secret of getting ahead is getting started' – Mark Twain",
	"'Everything you’ve ever wanted is on the other side of fear' – George Addair",
	"'Opportunities don’t happen, you create them' – Chris Grosser",
	"'Success usually comes to those who are too busy to be looking for it' – Henry David Thoreau",
	"'If you can dream it, you can do it' – Walt Disney",
	"'Little by little, one travels far' – J.R.R. Tolkien",
	"'The harder you work, the luckier you get' – Gary Player",
	"'Don’t stop when you’re tired. Stop when you’re done' – Anonymous",
	"'Great things never come from comfort zones' – Anonymous",
	"'Dream big and dare to fail' – Norman Vaughan",
	"'Success is the sum of small efforts, repeated day in and day out' – Robert Collier",
	"'You don’t have to be great to start, but you have to start to be great' – Zig Ziglar",
	"'The key to success is to focus on goals, not obstacles' – Anonymous",
	"'Failure will never overtake me if my determination to succeed is strong enough' – Og Mandino",
	"'Be yourself; everyone else is already taken' – Oscar Wilde",
	"'Do one thing every day that scares you' – Eleanor Roosevelt",
	"'Be the change that you wish to see in the world' – Mahatma Gandhi",
	"'If you’re going through hell, keep going' – Winston Churchill",
	"'Success is what happens after you have survived all of your mistakes' – Anonymous",
	"'The road to success and the road to failure are almost exactly the same' – Colin R. Davis",
	"'The best way to get ahead is to get started' – Anonymous",
	"'Doubt kills more dreams than failure ever will' – Suzy Kassem",
	"'Start where you are. Use what you have. Do what you can' – Arthur Ashe",
	"'What you get by achieving your goals is not as important as what you become by achieving your goals' – Zig Ziglar",
	"'It’s never too late to be what you might have been' – George Eliot",
	"'Perseverance is not a long race; it is many short races one after the other' – Walter Elliot",
	"'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart' – Roy T. Bennett",
	"'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle' – Christian D. Larson",
	"'If you’re not willing to risk the usual, you will have to settle for the ordinary' – Jim Rohn",
	"'You can never cross the ocean until you have the courage to lose sight of the shore' – Christopher Columbus",
	"'Your limitation is only your imagination' – Anonymous",
	"'Push yourself, because no one else is going to do it for you' – Anonymous",
	"'Great things never come from comfort zones' – Anonymous",
	"'Success doesn’t just find you. You have to go out and get it' – Anonymous",
	"'If you can’t stop thinking about it, don’t stop working for it' – Anonymous",
	"'The only way to achieve the impossible is to believe it is possible' – Charles Kingsleigh",
	"'Success is the result of preparation, hard work, and learning from failure' – Colin Powell",
	"'The dream is free. The hustle is sold separately' – Anonymous",
	"'A year from now you may wish you had started today' – Karen Lamb",
	"'When you feel like quitting, remember why you started' – Anonymous",
	"'Don’t wait for opportunity. Create it' – Anonymous",
	"'Do what you love and you’ll never work another day in your life' – Confucius",
	"'Work hard, stay consistent, and be patient' – Anonymous",
	"'Stop being afraid of what could go wrong, and start being excited about what could go right' – Tony Robbins",
	"'Success is not about the destination, it’s about the journey' – Zig Ziglar",
	"'It’s not about perfect. It’s about effort' – Jillian Michaels",
	"'Success is the ability to go from one failure to another with no loss of enthusiasm' – Winston Churchill",
	"'You must expect great things of yourself before you can do them' – Michael Jordan",
	"'Opportunities are usually disguised as hard work, so most people don’t recognize them' – Ann Landers",
	"'The difference between who you are and who you want to be is what you do' – Anonymous",
	"'Success is a journey, not a destination' – Arthur Ashe",
	"'The best revenge is massive success' – Frank Sinatra",
	"'Success is achieved and maintained by those who try and keep trying' – W. Clement Stone",
	"'Don’t count the days, make the days count' – Muhammad Ali",
	"'If you want to live a happy life, tie it to a goal, not to people or things' – Albert Einstein",
	"'Life is what happens when you’re busy making other plans' – John Lennon",
	"'It’s hard to beat a person who never gives up' – Babe Ruth",
	"'You miss 100% of the shots you don’t take' – Wayne Gretzky",
	"'The way to get started is to quit talking and begin doing' – Walt Disney",
	"'Success doesn’t come from what you do occasionally, it comes from what you do consistently' – Marie Forleo",
	"'Don’t be afraid to give up the good to go for the great' – John D. Rockefeller",
	"'Action is the foundational key to all success' – Pablo Picasso",
	"'Success is not in what you have, but who you are' – Bo Bennett",
	"'When you want to succeed as bad as you want to breathe, then you’ll be successful' – Eric Thomas",
	"'Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do' – Anonymous",
	"'The way to get started is to quit talking and begin doing' – Walt Disney",
	"'Success is the result of preparation, hard work, and learning from failure' – Colin Powell",
	"'The journey of a thousand miles begins with one step' – Laozi",
	"'He who learns but does not think, is lost. He who thinks but does not learn is in great danger' – Confucius",
	"'A bird does not sing because it has an answer. It sings because it has a song' – Chinese proverb",
	"'You cannot prevent the birds of sorrow from flying over your head, but you can prevent them from building nests in your hair' – Chinese proverb",
	"'Do not fear mistakes. You will know failure. Continue to reach out' – Confucius",
	"'He who conquers himself is the mightiest warrior' – Confucius",
	"'A gem cannot be polished without friction, nor a man perfected without trials' – Chinese proverb",
	"'The superior man is modest in his speech but exceeds in his actions' – Confucius",
	"'Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power' – Laozi",
	"'The wise adapt themselves to circumstances, as water molds itself to the pitcher' – Chinese proverb",
	"'To see a world in a grain of sand, and heaven in a wild flower, hold infinity in the palm of your hand, and eternity in an hour' – William Blake",
	"'The more that you read, the more things you will know. The more that you learn, the more places you’ll go' – Chinese proverb",
	"'When the character of a man is not clear to you, look at his friends' – Confucius",
	"'Silence is a source of great strength' – Laozi",
	"'It is better to light one small candle than to curse the darkness' – Confucius",
	"'Man who waits for roast duck to fly into mouth must wait very, very long time' – Chinese proverb",
	"'Tao is simple and pure, yet all things arise from it' – Laozi",
	"'You cannot open a book without learning something' – Confucius",
	"'Those who are wise do not seek to be known as wise' – Laozi",
	"'What you don’t want done to yourself, don’t do to others' – Confucius",
	"'If you want happiness for a lifetime, help someone else' – Chinese proverb",
	"'Learning without thought is labor lost; thought without learning is perilous' – Confucius",
	"'A true friend is someone who is there for you when he’d rather be anywhere else' – Chinese proverb",
	"'Silence is the sleep that nourishes wisdom' – Chinese proverb",
	"'The greatest wealth is to live content with little' – Laozi",
	"'The more you know, the less you need' – Chinese proverb",
	"'A good traveler has no fixed plans, and is not intent on arriving' – Laozi",
	"'A person who has committed a mistake and doesn’t correct it is committing another mistake' – Confucius",
	"'The superior man acts before he speaks, and afterwards speaks according to his actions' – Confucius",
	"'To live is to suffer, to survive is to find some meaning in the suffering' – Friedrich Nietzsche (also resonant with Chinese Buddhism)",
	"'The wise man does not seek to dominate, but to understand' – Laozi",
	"'With time and patience, the mulberry leaf becomes a silk gown' – Chinese proverb",
	"'Water does not resist. Water flows. When you plunge your hand into it, you feel its warmth. When you let go, it returns to its original state' – Taoist proverb",
	"'He who has a why to live can bear almost any how' – Friedrich Nietzsche",
	"'Greatness is not in where we stand, but in what direction we are moving' – Confucius",
	"'If you wish to climb high, you must begin at the bottom' – Chinese proverb",
	"'The three treasures of the Tao: simplicity, patience, and compassion' – Laozi",
	"'The greatest glory is not in never falling, but in rising every time we fall' – Confucius",
	"'A bird who dares to fall is the bird who learns to fly' – Chinese proverb",
	"'Wherever you go, go with all your heart' – Confucius",
	"'True love is eternal, infinite, and always like itself' – Chinese proverb",
	"'Time flies like an arrow, fruit flies like a banana' – Chinese proverb",
	"'The one who cherishes the truth is a sage; the one who cherishes power is a tyrant' – Chinese proverb",
	"'Failure is the foundation of success; success is the lurking place of failure' – Laozi",
	"'A kind word can warm three winter months' – Japanese proverb",
	"'What you do not want done to yourself, do not do to others' – Confucius",
	"'You don’t have to be great to start, but you have to start to be great' – Confucius",
	"'The sun may shine bright, but without the moon, it’s not complete' – Chinese proverb",
	"'Wealth consists not in having great possessions, but in having few wants' – Epictetus (influenced by Taoist thinking)",
	"'A penny saved is a penny earned' – Chinese proverb",
	"'To live is to suffer, to survive is to find some meaning in the suffering' – Friedrich Nietzsche",
	"'The snow goose need not bathe to make itself white. Neither need you do anything except be yourself' - Anonymous",
	"'The best time to plant a tree was 20 years ago. The second-best time is now' – Chinese proverb",
	"'When the wind blows, the grass bends' – Chinese proverb",
	"'The bird who dares to fall is the bird who learns to fly' – Chinese proverb",
	"'Do not go where the path may lead, go instead where there is no path and leave a trail' – Chinese proverb",
	"'Silence is the sleep that nourishes wisdom' – Chinese proverb",
	"'Patience and time do more than strength or passion' – Chinese proverb",
	"'A person who has committed a mistake and doesn’t correct it is committing another mistake' – Confucius",
	"'Rivers know this: There is no hurry. We shall get there someday' – A.A. Milne",
	"'With time and patience, the mulberry leaf becomes a silk gown' – Chinese proverb",
	"'The more you know, the less you need' – Chinese proverb",
	"'Life is really simple, but we insist on making it complicated' – Confucius",
	"'He who asks is a fool for five minutes, but he who does not ask remains a fool forever' – Chinese proverb",
	"'A true friend is someone who is there for you when he’d rather be anywhere else' – Chinese proverb",
	"'Learning is a treasure that will follow its owner everywhere' – Chinese proverb",
	"'A smile will gain you ten more years of life' – Chinese proverb",
	"'A penny saved is a penny earned' – Chinese proverb",
	"'The superior man acts before he speaks, and afterwards speaks according to his actions' – Confucius",
	"'Learn as if you will live forever, live like you will die tomorrow' – Chinese proverb",
	"'A person who does not learn is like a house with no foundation' – Chinese proverb",
	"'To lead people, walk behind them' – Laozi",
	"'A fool believes that the world owes him a living; a wise man knows that he must earn it' – Chinese proverb",
	"'Never be deceived that the rich will allow you to vote away their wealth'' – Lucy Parsons",
	"'To be rich is not enough; you must know how to use your riches' – Chinese proverb",
	"'Do not go where the path may lead, go instead where there is no path and leave a trail' – Chinese proverb",
	"'A man who moves a mountain begins by carrying away small stones' – Chinese proverb",
	"'A gentleman’s feelings are expressed in his actions, not in his words' – Confucius",
	"'The greatest wealth is to live content with little' – Chinese proverb",
	"'The wise man does not seek to dominate, but to understand' – Laozi",
	"'A fool only learns from his own mistakes. The wise man learns from the mistakes of others' – Chinese proverb",
	"'Be like water. Go with the flow' – Chinese proverb",
	"'Sow good seeds and you shall harvest good fruits' – Chinese proverb",
	"'What the caterpillar calls the end of the world, the master calls a butterfly' – Laozi",
	"'No matter how tall the mountain is, it cannot block the sun' – Chinese proverb",
	"'The moon does not fight. It attacks no one. It just shines' – Chinese proverb",
	"'One joy scatters a hundred grieves' – Chinese proverb",
	"'Silence is the sleep that nourishes wisdom' – Chinese proverb",
	"'Patience and time do more than strength or passion' – Chinese proverb",
	"'A person who has committed a mistake and doesn’t correct it is committing another mistake' – Confucius",
	"'What you do not want done to yourself, do not do to others' – Confucius",
	"'Rivers know this: There is no hurry. We shall get there someday' – A.A. Milne",
	"'With time and patience, the mulberry leaf becomes a silk gown' – Chinese proverb",
	"'The more you know, the less you need' – Chinese proverb",
	"'Life is really simple, but we insist on making it complicated' – Confucius",
	"'He who asks is a fool for five minutes, but he who does not ask remains a fool forever' – Chinese proverb",
	"'A true friend is someone who is there for you when he’d rather be anywhere else' – Chinese proverb",
	"'The journey of a thousand miles begins with one step' – Laozi",
	"'You don’t have to be great to start, but you have to start to be great' – Confucius",
	"'The sun may shine bright, but without the moon, it’s not complete' – Chinese proverb",
	"'Wealth consists not in having great possessions, but in having few wants' – Epictetus",
}

print("|cFF00FF00Message of the day - |r" .. messageName[math.random(1, #messageName)])


